tap 'thoughtbot/formulae'

brew 'asdf'
brew 'coreutils'
brew 'ctags'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'macvim'
brew 'the_silver_searcher'
brew 'thoughtbot/formulae/gitsh'
brew 'thoughtbot/formulae/rcm'
brew 'tmux'
brew 'zsh'
