#!/bin/sh

set -e

echo ""
echo "==========================================="
if [ "$(uname -s)" = "Linux" ]; then
  deps="fzf silversearcher-ag rcm tmux zsh"
  sudo apt-get install $deps

  script/install-gitsh
elif [ "$(uname -s)" = "Darwin" ]; then
  echo ""
  echo "==========================================="
  echo "Setting up Homebrew"
  echo ""

  echo "Installing Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
    || echo "Homebrew already installed"

  echo "Installing brew bundle"
  brew tap Homebrew/bundle

  echo "Installing homebrew dependencies"
  brew bundle
fi
