#!/bin/sh

set -e

echo ""
echo "==========================================="
echo "Setting up dotfiles"
echo ""


echo "Using RCM to symlink dotfiles"
if [ "$CODESPACES" = true ]; then
  RCRC=./rcrc rcup -vf -d /workspaces/.codespaces/.persistedshare/dotfiles
else
  RCRC=rcrc rcup -v
fi
